[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --ignore-scripts"]

[phases.build]
cmds = ["pnpm run build --filter=@workspace/api-server"]

[start]
cmd = "pnpm run start --filter=@workspace/api-server"
