[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --ignore-scripts"]

[phases.build]
cmds = ["npm run build --workspace=artifacts/api-server"]

[start]
cmd = "npm run start --workspace=artifacts/api-server"
