ALTER TABLE profiles
ADD COLUMN can_create_events BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN can_view_kpis BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN can_view_members BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN can_view_attendance BOOLEAN NOT NULL DEFAULT TRUE;